Update script output

diff --git a/cvbuild b/cvbuild
--- a/cvbuild
+++ b/cvbuild
@@ -2,7 +2,7 @@
 
 #=== SH_SCRIPT  ================================================================
 #         NAME:   CVBuild
-#  DESCRIPTION:   Short description
+#  DESCRIPTION:   A script to build a Awesome LaTeX CV into a PDF file.
 #         DATE:   2022/05/21
 #===============================================================================
 
@@ -17,34 +17,34 @@
 set -euo pipefail
 
 SCRIPT_VERSION="0.1"
-SHORT_DESCRIPTION="Short description"
-SCRIPT_NAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
+SHORT_DESCRIPTION="A script to build a Awesome LaTeX CV into a PDF file."
+SCRIPT_NAME="CVBuild"
+SCRIPT_RUN="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
 
 
-#====  FUNCTION  ================================================================
-#         NAME:   version
-#  DESCRIPTION:   Show script name, script version and short description
+#===  FUNCTION  ================================================================
+#         NAME:   Version
+#  DESCRIPTION:   Show script name, script version and short description.
 #===============================================================================
 function version()
 {
-    echo -e "$SCRIPT_NAME $SCRIPT_VERSION $SHORT_DESCRIPTION"
+    echo -e "$SCRIPT_NAME v$SCRIPT_VERSION, ${SHORT_DESCRIPTION,}"
 
 }  # ------------  end of function version  ------------
 
 
-#====  FUNCTION  ================================================================
+#===  FUNCTION  ================================================================
 #         NAME:   help
 #  DESCRIPTION:   Show the script usage and documentation help
 #===============================================================================
 function help()
 {
-    echo -e "Usage: $SCRIPT_NAME [OPTION]... [FILE]
-     $SCRIPT_NAME [OPTION]... [FILE] [OUTFILE]
+    echo -e "Usage: $SCRIPT_RUN [OPTION]... [FILE]
+       $SCRIPT_RUN [OPTION]... [FILE] [OUTFILE]
 
-    Options:
-    -p|presentation [FILE]  Replace default presentation text with [FILE]
-    -h|help                 Display this message
-    -v|version    Display script version"
+Options:
+  -h|help          Display this message
+  -v|version       Display script version"
 
 }  # ------------  end of function help  ------------
 
@@ -52,26 +52,20 @@ function help()
 #-------------------------------------------------------------------------------
 #  Handle command line arguments
 #-------------------------------------------------------------------------------
-while getopts ":hvr:i:o:" opt
+while getopts ":hv" opt
     do
         case $opt in
-            r|resume)
-                ;;
-            i|input)
-                ;;
-            o|output)
-                ;;
             h|help)
                 version
                 help
                 exit 0
                 ;;
             v|version)
-                echo " -- Version $__ScriptVersion"
+                version
                 exit 0
                 ;;
             *)
-                echo -e "$SCRIPT_NAME: Invalid option -- '$opt'"
+                echo -e "$SCRIPT_NAME: Invalid option -- '-$OPTARG'"
                 help
                 exit 1
                 ;;
