feat: Apply formatter

diff --git a/cvbuild b/cvbuild
--- a/cvbuild
+++ b/cvbuild
@@ -13,7 +13,6 @@
 # x - output each line (debug)
 set -euo pipefail
 
-
 #-----------------------------------------------------------------------
 #  Global settings
 #-----------------------------------------------------------------------
@@ -25,10 +24,9 @@ DEFAULT_INPUT_FILE="curriculum"
 DEFAULT_LETTER="carta"
 DEFAULT_EN_LETTER="letter"
 TEMP_FILE="_temp_cvbuild_file"
-VERBOSE_BUILD=false
+VERBOSE_BUILD=false # silent, quiet
 
-DEPENDENCIES=( "xelatex" "xdg-open" )
-
+DEPENDENCIES=("xelatex" "xdg-open")
 
 #----------------------------------------
 # Terminal output font styles and colors
@@ -37,7 +35,7 @@ ORANGE="\033[0;33m"
 RED="\e[31m"
 BLD="\033[1m" # Bold
 ITL="\033[3m" # Italic
-NS="\033[0m" # No style
+NS="\033[0m"  # No style
 
 STLCMD="\033[1;36m"
 STLOPT="\033[1;32m"
@@ -47,44 +45,37 @@ STLERR="\e[0;31m"
 # HACK: Get the real script filename even through a symbolic link
 SCRIPT_RUN="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
 
-
 #-----------------------------------------------------------------------
 # Check dependencies
 #-----------------------------------------------------------------------
 missing_deps=0
 for dependency in "${DEPENDENCIES[@]}"; do
-    if ! command -v "$dependency" > /dev/null 2>&1; then
-        echo -e "$RED$SCRIPT_RUN: Could't find '$dependency' on the system."\
-                                 "Check if is installed.$NS"
-        ((++missing_deps))
-    fi
+  if ! command -v "$dependency" >/dev/null 2>&1; then
+    echo -e "$RED$SCRIPT_RUN: Could't find '$dependency' on the system." \
+      "Check if is installed.$NS"
+    ((++missing_deps))
+  fi
 done
 if [[ $missing_deps -gt 0 ]]; then
-    exit 1
+  exit 1
 fi
-
-
 
 #===  FUNCTION  ================================================================
 #         NAME:   Version
 #  DESCRIPTION:   Show script name, script version and short description.
 #===============================================================================
-function version()
-{
-    echo -e "$BLD$SCRIPT_NAME v$SCRIPT_VERSION$NS"
-    echo -e "$ITL$SHORT_DESCRIPTION$NS\n"
+function version() {
+  echo -e "$BLD$SCRIPT_NAME v$SCRIPT_VERSION$NS"
+  echo -e "$ITL$SHORT_DESCRIPTION$NS\n"
 
-}  # ------------  end of function version  ------------
-
-
+} # ------------  end of function version  ------------
 
 #===  FUNCTION  ================================================================
 #         NAME:   Help
 #  DESCRIPTION:   Show the script usage and documentation help
 #===============================================================================
-function help()
-{
-    echo -e "${BLD}Usage: ${STLCMD}${SCRIPT_RUN} ${STLARG}[FILE]
+function help() {
+  echo -e "${BLD}Usage: ${STLCMD}${SCRIPT_RUN} ${STLARG}[FILE]
        ${STLCMD}${SCRIPT_RUN} ${STLARG}[OPTION]... [FILE] [OUTFILE]
        ${STLCMD}${SCRIPT_RUN} ${STLARG}-l [OUTFILE]${NS}
 Make a filename.pdf (or OUTFILE) from the input tex FILE.
@@ -103,9 +94,7 @@ ${STLOPT}  -i (images)              ${NS}Generate preview images.
 ${STLOPT}  -h (help)                ${NS}Display this help message.
 ${STLOPT}  -v (version)             ${NS}Display the version of ${SCRIPT_NAME} and exit."
 
-}  # ------------  end of function help  ------------
-
-
+} # ------------  end of function help  ------------
 
 #===  FUNCTION  ================================================================
 #         NAME:   Set english
@@ -113,18 +102,15 @@ ${STLOPT}  -v (version)             ${NS}Display the version of ${SCRIPT_NAME} a
 #    ARGUMENTS:   $1: File to edit.
 #                 $2: Boolean value
 #===============================================================================
-function set_english()
-{
-    if [ "$2" = true ]; then
-        echo -en "${ITL}Setting language to english...${NS} "
-        sed -i 's/\\spanishtrue/\\spanishfalse/' "$1"
-        echo -e "${GREEN}OK.$NS"
-    else
-        sed -i 's/\\spanishfalse/\\spanishtrue/' "$1"
-    fi
-}  # ------------  end of function set_english  ------------
-
-
+function set_english() {
+  if [ "$2" = true ]; then
+    echo -en "${ITL}Setting language to english...${NS} "
+    sed -i 's/\\spanishtrue/\\spanishfalse/' "$1"
+    echo -e "${GREEN}OK.$NS"
+  else
+    sed -i 's/\\spanishfalse/\\spanishtrue/' "$1"
+  fi
+} # ------------  end of function set_english  ------------
 
 #-------------------------------------------------------------------------------
 #  Default variables
@@ -140,115 +126,107 @@ watch=false
 need_backup=false
 english=false
 
-
 #-------------------------------------------------------------------------------
 #  Handle command line arguments
 #-------------------------------------------------------------------------------
-while getopts ":p:o:liewhv" opt
-    do
-        case $opt in
-            p) # Presentation
-                presentation_file=$OPTARG
-                ;;
-            o) # Output file
-                output_file=$OPTARG
-                ((max_args--))
-                ;;
-            l) # Letter mode
-                letter_mode=true
-                ((max_args--))
-                ;;
-            i) # Images mode
-                images_mode=true
-                ((max_args--))
-                ;;
-            e) # Set english mode
-                english=true
-                ((max_args--))
-                ;;
-            w) # Watch, open after
-                watch=true
-                ;;
-            h) # Help
-                version
-                help
-                exit 0
-                ;;
-            v) # Version
-                version
-                exit 0
-                ;;
-            :)
-                echo -e "$STLERR$SCRIPT_NAME:"\
-                        "Invalid option -- '-$OPTARG' requires an argument$NS\n"
-                help
-                exit 1
-                ;;
-            *)
-                echo -e "$STLERR$SCRIPT_NAME: Invalid option -- '-$OPTARG'$NS\n"
-                help
-                exit 1
-                ;;
-    esac
-done    # ----------  end of getopts handler  ----------
-shift $((OPTIND-1))
-
+while getopts ":p:o:liewhv" opt; do
+  case $opt in
+  p) # Presentation
+    presentation_file=$OPTARG
+    ;;
+  o) # Output file
+    output_file=$OPTARG
+    ((max_args--))
+    ;;
+  l) # Letter mode
+    letter_mode=true
+    ((max_args--))
+    ;;
+  i) # Images mode
+    images_mode=true
+    ((max_args--))
+    ;;
+  e) # Set english mode
+    english=true
+    ((max_args--))
+    ;;
+  w) # Watch, open after
+    watch=true
+    ;;
+  h) # Help
+    version
+    help
+    exit 0
+    ;;
+  v) # Version
+    version
+    exit 0
+    ;;
+  :)
+    echo -e "$STLERR$SCRIPT_NAME:" \
+      "Invalid option -- '-$OPTARG' requires an argument$NS\n"
+    help
+    exit 1
+    ;;
+  *)
+    echo -e "$STLERR$SCRIPT_NAME: Invalid option -- '-$OPTARG'$NS\n"
+    help
+    exit 1
+    ;;
+  esac
+done # ----------  end of getopts handler  ----------
+shift $((OPTIND - 1))
 
 #-------------------------------------------------------------------------------
 # Check for extra arguments, bad combinations and get IN/OUT files
 #-------------------------------------------------------------------------------
 if [[ $# -gt max_args ]]; then
-    echo -e "$RED$SCRIPT_NAME: Unable to infer IN/OUT file."\
-            "Read script usage.$NS\n"
-    exit 1
+  echo -e "$RED$SCRIPT_NAME: Unable to infer IN/OUT file." \
+    "Read script usage.$NS\n"
+  exit 1
 fi
 
 if [[ $letter_mode = true && $presentation_file != "" ]]; then
-    echo -e "$RED$SCRIPT_NAME: Letter and presentation can't be"\
-            "used at the same time.$NS"
-    exit 1
+  echo -e "$RED$SCRIPT_NAME: Letter and presentation can't be" \
+    "used at the same time.$NS"
+  exit 1
 fi
 
 # If letter mode is used, then no input file is needed and the
 # remaining arg should be outfile.
 if [[ $letter_mode = true && $# -eq 1 ]]; then
-    output_file=$1
-    shift
+  output_file=$1
+  shift
 # Either -o is used or not, the first remaining arg should be the inputfile
 elif [[ $# -gt 0 ]]; then
-    input_file=$1
-    shift
+  input_file=$1
+  shift
 fi
 # Lastly if no '-o' is passed there could be a outfile arg remaining
 if [[ $# -gt 0 ]]; then
-    output_file=$1
-    shift
+  output_file=$1
+  shift
 fi
-
-
 
 #===  FUNCTION  ================================================================
 #         NAME:   Check file
 #  DESCRIPTION:   Check if the passed FILE exist.
 #    ARGUMENTS:   $1: FILE, $2: Description
 #===============================================================================
-function check_file()
-{
-    echo -en "Checking ${2,,}: $ORANGE'$1'$NS... "
-    # -d check a directory
-    if [[ -d $1 ]]; then
-        echo -e "\n${RED}$SCRIPT_RUN: '$1': Is a directory.$NS"
-        exit 1
-    # -f check if file exist
-    elif [[ ! -f $1 ]]; then
-        echo -e "\n${RED}$SCRIPT_RUN: '$1': No such file or directory.$NS"
-        exit 1
-    fi
-    echo -e "${GREEN}OK.$NS"
+function check_file() {
+  echo -en "Checking ${2,,}: $ORANGE'$1'$NS... "
+  # -d check a directory
+  if [[ -d $1 ]]; then
+    echo -e "\n${RED}$SCRIPT_RUN: '$1': Is a directory.$NS"
+    exit 1
+  # -f check if file exist
+  elif [[ ! -f $1 ]]; then
+    echo -e "\n${RED}$SCRIPT_RUN: '$1': No such file or directory.$NS"
+    exit 1
+  fi
+  echo -e "${GREEN}OK.$NS"
 
-}  # ------------  end of function check_file  ------------
-
-
+} # ------------  end of function check_file  ------------
 
 #===  FUNCTION  ================================================================
 #         NAME:   Change presentation
@@ -256,44 +234,38 @@ function check_file()
 #                 the presentation file with the setted one on the copied file.
 #    ARGUMENTS:   $1: Input file, $2: Presentation file
 #===============================================================================
-function change_presentation()
-{
-    echo -en "Replacing presentation file with: $ORANGE'$1'$NS... "
-    cp "$1" "$TEMP_FILE"
-    # $1 could contain '/' so we need to make the substitution inside call
-    sed -i "s/\\input{sections\/resumen.tex}/\\input\{${2//\//\\/}\}/" "$TEMP_FILE"
-    echo -e "${GREEN}OK.$NS"
+function change_presentation() {
+  echo -en "Replacing presentation file with: $ORANGE'$1'$NS... "
+  cp "$1" "$TEMP_FILE"
+  # $1 could contain '/' so we need to make the substitution inside call
+  sed -i "s/\\input{sections\/resumen.tex}/\\input\{${2//\//\\/}\}/" "$TEMP_FILE"
+  echo -e "${GREEN}OK.$NS"
 
-}  # ------------  end of function change_presentation  ------------
-
-
+} # ------------  end of function change_presentation  ------------
 
 #===  FUNCTION  ================================================================
 #         NAME:   Make PDF
 #  DESCRIPTION:   Build the PDF file with xelatex
 #    ARGUMENTS:   $1: Target, $2: bool, if true passed $3: base file for message
 #===============================================================================
-function make_pdf()
-{
-    if [[ $2 = true ]]; then
-        _source_tex="$3"
-    else
-        _source_tex="$1"
-    fi
-    echo -e "Generating PDF file from $ORANGE'$_source_tex'$NS with xelatex..."
-    echo -e "-----------------------------------------------------------"
+function make_pdf() {
+  if [[ $2 = true ]]; then
+    _source_tex="$3"
+  else
+    _source_tex="$1"
+  fi
+  echo -e "Generating PDF file from $ORANGE'$_source_tex'$NS with xelatex..."
+  echo -e "-----------------------------------------------------------"
 
-    if [[ $VERBOSE_BUILD = true ]]; then
-        xelatex -synctex=1 -halt-on-error "$1"
-    else
-        xelatex -synctex=1 -interaction=batchmode -halt-on-error "$1"
-    fi
-    #echo -e "\n${GREEN}OK.$NS\nFile$ORANGE ${2%.*}.pdf$NS has been generated."
-    echo -e "\n-----------------------------------------------------------"
+  if [[ $VERBOSE_BUILD = true ]]; then
+    xelatex -synctex=1 -halt-on-error "$1"
+  else
+    xelatex -synctex=1 -interaction=batchmode -halt-on-error "$1"
+  fi
+  #echo -e "\n${GREEN}OK.$NS\nFile$ORANGE ${2%.*}.pdf$NS has been generated."
+  echo -e "\n-----------------------------------------------------------"
 
-}  # ------------  end of function make_pdf  ------------
-
-
+} # ------------  end of function make_pdf  ------------
 
 #===============================================================================
 # BEGINNING OF SCRIPT WORK
@@ -303,40 +275,39 @@ function make_pdf()
 # Generate images from existing pdf
 #-------------------------------------------------------------------------------
 if [[ $images_mode = true ]]; then
-    echo -e "Generating images..."
-    convert -density 150 curriculum.pdf[0] -background white -alpha remove -quality 90 images/preview-1.png
-    convert -density 150 curriculum.pdf[1] -background white -alpha remove -quality 90 images/preview-2.png
-    echo -e "Done"
-    exit
+  echo -e "Generating images..."
+  convert -density 150 curriculum.pdf[0] -background white -alpha remove -quality 90 images/preview-1.png
+  convert -density 150 curriculum.pdf[1] -background white -alpha remove -quality 90 images/preview-2.png
+  echo -e "Done"
+  exit
 fi
-
 
 #-------------------------------------------------------------------------------
 # Prepare paths
 #-------------------------------------------------------------------------------
 if [[ $letter_mode = true && $english = true ]]; then
-    input_file="$DEFAULT_EN_LETTER.tex"
+  input_file="$DEFAULT_EN_LETTER.tex"
 elif [[ $letter_mode = true ]]; then
-    input_file="$DEFAULT_LETTER.tex"
+  input_file="$DEFAULT_LETTER.tex"
 elif [[ $input_file == "" ]]; then
-    input_file="$DEFAULT_INPUT_FILE.tex"
+  input_file="$DEFAULT_INPUT_FILE.tex"
 elif [[ $input_file != *.tex ]]; then
-    input_file="$input_file.tex"
+  input_file="$input_file.tex"
 fi
 
 if [[ $output_file == "" ]]; then
-    if [[ $letter_mode = true && $english = true ]]; then
-        output_file="$DEFAULT_EN_LETTER.pdf"
-    elif [[ $letter_mode = true ]]; then
-        output_file="$DEFAULT_LETTER.pdf"
+  if [[ $letter_mode = true && $english = true ]]; then
+    output_file="$DEFAULT_EN_LETTER.pdf"
+  elif [[ $letter_mode = true ]]; then
+    output_file="$DEFAULT_LETTER.pdf"
 
-    elif [[ $english = true ]]; then
-        output_file="${DEFAULT_INPUT_FILE}_en.pdf"
-    else
-        output_file="$DEFAULT_INPUT_FILE.pdf"
-    fi
+  elif [[ $english = true ]]; then
+    output_file="${DEFAULT_INPUT_FILE}_en.pdf"
+  else
+    output_file="$DEFAULT_INPUT_FILE.pdf"
+  fi
 elif [[ $output_file != *.pdf ]]; then
-    output_file="$output_file.pdf"
+  output_file="$output_file.pdf"
 fi
 
 #-------------------------------------------------------------------------------
@@ -350,41 +321,40 @@ set_english "$input_file" "$english"
 # as output, then the existing cv.pdf should be preserved. Therefore we need
 # make a backup before the make_pdf function.
 if [[ ${input_file%.*} != "${output_file%.*}" && -f ${input_file%.*}.pdf ]]; then
-    need_backup=true
+  need_backup=true
 fi
 
 if [[ $presentation_file != "" ]]; then
-    check_file "$presentation_file" "presentation file"
-    change_presentation "$input_file" "$presentation_file"
-    make_pdf "$TEMP_FILE" true "$input_file"
-    echo -e "${GREEN}OK.$NS PDF file has been generated."
+  check_file "$presentation_file" "presentation file"
+  change_presentation "$input_file" "$presentation_file"
+  make_pdf "$TEMP_FILE" true "$input_file"
+  echo -e "${GREEN}OK.$NS PDF file has been generated."
 
-    mv "$TEMP_FILE.pdf" "$output_file"
-    echo -e "File$ORANGE $output_file$NS with $ORANGE'$presentation_file'$NS"\
-            "has\nbeen successfully generated."
-    rm "$TEMP_FILE*"
+  mv "$TEMP_FILE.pdf" "$output_file"
+  echo -e "File$ORANGE $output_file$NS with $ORANGE'$presentation_file'$NS" \
+    "has\nbeen successfully generated."
+  rm "$TEMP_FILE*"
 else
-    if [[ $need_backup = true ]]; then
-        mv "${input_file%.*}.pdf" "$TEMP_FILE.pdf"
-    fi
+  if [[ $need_backup = true ]]; then
+    mv "${input_file%.*}.pdf" "$TEMP_FILE.pdf"
+  fi
 
-    make_pdf "$input_file" false
-    if [[ "${input_file%.*}.pdf" != "$output_file" ]]; then
-        mv "${input_file%.*}.pdf" "$output_file"
-    fi
+  make_pdf "$input_file" false
+  if [[ "${input_file%.*}.pdf" != "$output_file" ]]; then
+    mv "${input_file%.*}.pdf" "$output_file"
+  fi
 
-    # Restore the backup if needed
-    if [[ $need_backup = true ]]; then
-        mv "$TEMP_FILE.pdf" "${input_file%.*}.pdf"
-    fi
-    echo -e "File$ORANGE '${output_file}'$NS has been successfully generated."
+  # Restore the backup if needed
+  if [[ $need_backup = true ]]; then
+    mv "$TEMP_FILE.pdf" "${input_file%.*}.pdf"
+  fi
+  echo -e "File$ORANGE '${output_file}'$NS has been successfully generated."
 fi
 
 #----------------------------------------
 # Open the generated file
 if [[ $watch = true ]]; then
-    xdg-open "${output_file}" 2> /dev/null
+  xdg-open "${output_file}" 2>/dev/null
 fi
 
 exit 0
-
